
(executable
  (name Hacl_Hash_Blake2_gen)
  (modules Hacl_Hash_Blake2_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_Blake2_bindings ctypes.stubs))

(executable
  (name Hacl_Streaming_SHA2_gen)
  (modules Hacl_Streaming_SHA2_gen)
  (libraries lib_evercrypt_so lib_Hacl_Streaming_SHA2_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_Base_gen)
  (modules Hacl_Hash_Base_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_Base_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_Blake2b_256_gen)
  (modules Hacl_Hash_Blake2b_256_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_Blake2b_256_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_Blake2s_128_gen)
  (modules Hacl_Hash_Blake2s_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_Blake2s_128_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_MD5_gen)
  (modules Hacl_Hash_MD5_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_MD5_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_SHA1_gen)
  (modules Hacl_Hash_SHA1_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_SHA1_bindings ctypes.stubs))

(executable
  (name Hacl_Hash_SHA2_gen)
  (modules Hacl_Hash_SHA2_gen)
  (libraries lib_evercrypt_so lib_Hacl_Hash_SHA2_bindings ctypes.stubs))

(executable
  (name EverCrypt_AutoConfig2_gen)
  (modules EverCrypt_AutoConfig2_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_AutoConfig2_bindings ctypes.stubs))

(executable
  (name EverCrypt_Hash_gen)
  (modules EverCrypt_Hash_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Hash_bindings ctypes.stubs))

(executable
  (name Hacl_SHA3_gen)
  (modules Hacl_SHA3_gen)
  (libraries lib_evercrypt_so lib_Hacl_SHA3_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20_gen)
  (modules Hacl_Chacha20_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20_bindings ctypes.stubs))

(executable
  (name Hacl_Salsa20_gen)
  (modules Hacl_Salsa20_gen)
  (libraries lib_evercrypt_so lib_Hacl_Salsa20_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum_Base_gen)
  (modules Hacl_Bignum_Base_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum_Base_bindings ctypes.stubs))

(executable
  (name Hacl_Curve25519_64_Slow_gen)
  (modules Hacl_Curve25519_64_Slow_gen)
  (libraries lib_evercrypt_so lib_Hacl_Curve25519_64_Slow_bindings ctypes.stubs))

(executable
  (name Hacl_Curve25519_64_gen)
  (modules Hacl_Curve25519_64_gen)
  (libraries lib_evercrypt_so lib_Hacl_Curve25519_64_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum25519_51_gen)
  (modules Hacl_Bignum25519_51_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum25519_51_bindings ctypes.stubs))

(executable
  (name Hacl_Curve25519_51_gen)
  (modules Hacl_Curve25519_51_gen)
  (libraries lib_evercrypt_so lib_Hacl_Curve25519_51_bindings ctypes.stubs))

(executable
  (name Hacl_Ed25519_gen)
  (modules Hacl_Ed25519_gen)
  (libraries lib_evercrypt_so lib_Hacl_Ed25519_bindings ctypes.stubs))

(executable
  (name Hacl_Poly1305_32_gen)
  (modules Hacl_Poly1305_32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Poly1305_32_bindings ctypes.stubs))

(executable
  (name Hacl_Poly1305_128_gen)
  (modules Hacl_Poly1305_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_Poly1305_128_bindings ctypes.stubs))

(executable
  (name Hacl_Poly1305_256_gen)
  (modules Hacl_Poly1305_256_gen)
  (libraries lib_evercrypt_so lib_Hacl_Poly1305_256_bindings ctypes.stubs))

(executable
  (name Hacl_NaCl_gen)
  (modules Hacl_NaCl_gen)
  (libraries lib_evercrypt_so lib_Hacl_NaCl_bindings ctypes.stubs))

(executable
  (name EverCrypt_CTR_gen)
  (modules EverCrypt_CTR_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_CTR_bindings ctypes.stubs))

(executable
  (name Hacl_P256_gen)
  (modules Hacl_P256_gen)
  (libraries lib_evercrypt_so lib_Hacl_P256_bindings ctypes.stubs))

(executable
  (name Hacl_Frodo_KEM_gen)
  (modules Hacl_Frodo_KEM_gen)
  (libraries lib_evercrypt_so lib_Hacl_Frodo_KEM_bindings ctypes.stubs))

(executable
  (name Hacl_IntTypes_Intrinsics_gen)
  (modules Hacl_IntTypes_Intrinsics_gen)
  (libraries lib_evercrypt_so lib_Hacl_IntTypes_Intrinsics_bindings ctypes.stubs))

(executable
  (name Hacl_IntTypes_Intrinsics_128_gen)
  (modules Hacl_IntTypes_Intrinsics_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_IntTypes_Intrinsics_128_bindings ctypes.stubs))

(executable
  (name Hacl_RSAPSS_gen)
  (modules Hacl_RSAPSS_gen)
  (libraries lib_evercrypt_so lib_Hacl_RSAPSS_bindings ctypes.stubs))

(executable
  (name Hacl_FFDHE_gen)
  (modules Hacl_FFDHE_gen)
  (libraries lib_evercrypt_so lib_Hacl_FFDHE_bindings ctypes.stubs))

(executable
  (name Hacl_Streaming_Blake2_gen)
  (modules Hacl_Streaming_Blake2_gen)
  (libraries lib_evercrypt_so lib_Hacl_Streaming_Blake2_bindings ctypes.stubs))

(executable
  (name Hacl_Frodo640_gen)
  (modules Hacl_Frodo640_gen)
  (libraries lib_evercrypt_so lib_Hacl_Frodo640_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20_Vec128_gen)
  (modules Hacl_Chacha20_Vec128_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20_Vec128_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20Poly1305_128_gen)
  (modules Hacl_Chacha20Poly1305_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20Poly1305_128_bindings ctypes.stubs))

(executable
  (name Hacl_HMAC_gen)
  (modules Hacl_HMAC_gen)
  (libraries lib_evercrypt_so lib_Hacl_HMAC_bindings ctypes.stubs))

(executable
  (name Hacl_HKDF_gen)
  (modules Hacl_HKDF_gen)
  (libraries lib_evercrypt_so lib_Hacl_HKDF_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP128_SHA512_gen)
  (modules Hacl_HPKE_Curve51_CP128_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP128_SHA512_bindings ctypes.stubs))

(executable
  (name Hacl_SHA2_Vec256_gen)
  (modules Hacl_SHA2_Vec256_gen)
  (libraries lib_evercrypt_so lib_Hacl_SHA2_Vec256_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum4096_gen)
  (modules Hacl_Bignum4096_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum4096_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20_Vec32_gen)
  (modules Hacl_Chacha20_Vec32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20_Vec32_bindings ctypes.stubs))

(executable
  (name EverCrypt_Ed25519_gen)
  (modules EverCrypt_Ed25519_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Ed25519_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum4096_32_gen)
  (modules Hacl_Bignum4096_32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum4096_32_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_P256_CP128_SHA256_gen)
  (modules Hacl_HPKE_P256_CP128_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_P256_CP128_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20_Vec256_gen)
  (modules Hacl_Chacha20_Vec256_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20_Vec256_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20Poly1305_256_gen)
  (modules Hacl_Chacha20Poly1305_256_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20Poly1305_256_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP256_SHA512_gen)
  (modules Hacl_HPKE_Curve51_CP256_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP256_SHA512_bindings ctypes.stubs))

(executable
  (name Hacl_SHA2_Scalar32_gen)
  (modules Hacl_SHA2_Scalar32_gen)
  (libraries lib_evercrypt_so lib_Hacl_SHA2_Scalar32_bindings ctypes.stubs))

(executable
  (name Hacl_Frodo976_gen)
  (modules Hacl_Frodo976_gen)
  (libraries lib_evercrypt_so lib_Hacl_Frodo976_bindings ctypes.stubs))

(executable
  (name Hacl_HMAC_Blake2s_128_gen)
  (modules Hacl_HMAC_Blake2s_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_HMAC_Blake2s_128_bindings ctypes.stubs))

(executable
  (name Hacl_HKDF_Blake2s_128_gen)
  (modules Hacl_HKDF_Blake2s_128_gen)
  (libraries lib_evercrypt_so lib_Hacl_HKDF_Blake2s_128_bindings ctypes.stubs))

(executable
  (name Hacl_GenericField64_gen)
  (modules Hacl_GenericField64_gen)
  (libraries lib_evercrypt_so lib_Hacl_GenericField64_bindings ctypes.stubs))

(executable
  (name Hacl_Frodo1344_gen)
  (modules Hacl_Frodo1344_gen)
  (libraries lib_evercrypt_so lib_Hacl_Frodo1344_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum32_gen)
  (modules Hacl_Bignum32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum32_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP128_SHA256_gen)
  (modules Hacl_HPKE_Curve51_CP128_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP128_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum256_32_gen)
  (modules Hacl_Bignum256_32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum256_32_bindings ctypes.stubs))

(executable
  (name Hacl_SHA2_Vec128_gen)
  (modules Hacl_SHA2_Vec128_gen)
  (libraries lib_evercrypt_so lib_Hacl_SHA2_Vec128_bindings ctypes.stubs))

(executable
  (name Hacl_Chacha20Poly1305_32_gen)
  (modules Hacl_Chacha20Poly1305_32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Chacha20Poly1305_32_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP32_SHA256_gen)
  (modules Hacl_HPKE_Curve51_CP32_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP32_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_Streaming_Poly1305_32_gen)
  (modules Hacl_Streaming_Poly1305_32_gen)
  (libraries lib_evercrypt_so lib_Hacl_Streaming_Poly1305_32_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP32_SHA512_gen)
  (modules Hacl_HPKE_Curve51_CP32_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP32_SHA512_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_P256_CP256_SHA256_gen)
  (modules Hacl_HPKE_P256_CP256_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_P256_CP256_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_P256_CP32_SHA256_gen)
  (modules Hacl_HPKE_P256_CP32_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_P256_CP32_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_Bignum64_gen)
  (modules Hacl_Bignum64_gen)
  (libraries lib_evercrypt_so lib_Hacl_Bignum64_bindings ctypes.stubs))

(executable
  (name Hacl_Frodo64_gen)
  (modules Hacl_Frodo64_gen)
  (libraries lib_evercrypt_so lib_Hacl_Frodo64_bindings ctypes.stubs))

(executable
  (name Hacl_Streaming_SHA1_gen)
  (modules Hacl_Streaming_SHA1_gen)
  (libraries lib_evercrypt_so lib_Hacl_Streaming_SHA1_bindings ctypes.stubs))

(executable
  (name Hacl_Streaming_MD5_gen)
  (modules Hacl_Streaming_MD5_gen)
  (libraries lib_evercrypt_so lib_Hacl_Streaming_MD5_bindings ctypes.stubs))

(executable
  (name Hacl_HMAC_Blake2b_256_gen)
  (modules Hacl_HMAC_Blake2b_256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HMAC_Blake2b_256_bindings ctypes.stubs))

(executable
  (name Hacl_HKDF_Blake2b_256_gen)
  (modules Hacl_HKDF_Blake2b_256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HKDF_Blake2b_256_bindings ctypes.stubs))

(executable
  (name Hacl_EC_Ed25519_gen)
  (modules Hacl_EC_Ed25519_gen)
  (libraries lib_evercrypt_so lib_Hacl_EC_Ed25519_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve51_CP256_SHA256_gen)
  (modules Hacl_HPKE_Curve51_CP256_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve51_CP256_SHA256_bindings ctypes.stubs))

(executable
  (name EverCrypt_Chacha20Poly1305_gen)
  (modules EverCrypt_Chacha20Poly1305_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Chacha20Poly1305_bindings ctypes.stubs))

(executable
  (name EverCrypt_AEAD_gen)
  (modules EverCrypt_AEAD_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_AEAD_bindings ctypes.stubs))

(executable
  (name EverCrypt_HMAC_gen)
  (modules EverCrypt_HMAC_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_HMAC_bindings ctypes.stubs))

(executable
  (name EverCrypt_HKDF_gen)
  (modules EverCrypt_HKDF_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_HKDF_bindings ctypes.stubs))

(executable
  (name Hacl_HMAC_DRBG_gen)
  (modules Hacl_HMAC_DRBG_gen)
  (libraries lib_evercrypt_so lib_Hacl_HMAC_DRBG_bindings ctypes.stubs))

(executable
  (name EverCrypt_DRBG_gen)
  (modules EverCrypt_DRBG_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_DRBG_bindings ctypes.stubs))

(executable
  (name EverCrypt_Poly1305_gen)
  (modules EverCrypt_Poly1305_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Poly1305_bindings ctypes.stubs))

(executable
  (name EverCrypt_Curve25519_gen)
  (modules EverCrypt_Curve25519_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Curve25519_bindings ctypes.stubs))

(executable
  (name EverCrypt_Cipher_gen)
  (modules EverCrypt_Cipher_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Cipher_bindings ctypes.stubs))

(executable
  (name EverCrypt_Vale_gen)
  (modules EverCrypt_Vale_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_Vale_bindings ctypes.stubs))

(executable
  (name EverCrypt_StaticConfig_gen)
  (modules EverCrypt_StaticConfig_gen)
  (libraries lib_evercrypt_so lib_EverCrypt_StaticConfig_bindings ctypes.stubs))

(executable
  (name Lib_RandomBuffer_System_gen)
  (modules Lib_RandomBuffer_System_gen)
  (libraries lib_evercrypt_so lib_Lib_RandomBuffer_System_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP128_SHA256_gen)
  (modules Hacl_HPKE_Curve64_CP128_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP128_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP128_SHA512_gen)
  (modules Hacl_HPKE_Curve64_CP128_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP128_SHA512_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP256_SHA256_gen)
  (modules Hacl_HPKE_Curve64_CP256_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP256_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP256_SHA512_gen)
  (modules Hacl_HPKE_Curve64_CP256_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP256_SHA512_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP32_SHA256_gen)
  (modules Hacl_HPKE_Curve64_CP32_SHA256_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP32_SHA256_bindings ctypes.stubs))

(executable
  (name Hacl_HPKE_Curve64_CP32_SHA512_gen)
  (modules Hacl_HPKE_Curve64_CP32_SHA512_gen)
  (libraries lib_evercrypt_so lib_Hacl_HPKE_Curve64_CP32_SHA512_bindings ctypes.stubs))
