
(library
  (name lib_Hacl_Hash_Blake2_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_Blake2-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_Blake2_bindings))

(library
  (name lib_Hacl_Streaming_SHA2_bindings)
  (public_name hacl-star-raw.lib-Hacl_Streaming_SHA2-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Streaming_SHA2_bindings))

(library
  (name lib_Hacl_Bignum_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum_bindings))

(library
  (name lib_Hacl_Hash_Base_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_Base-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_Base_bindings))

(library
  (name lib_Hacl_Hash_Blake2b_256_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_Blake2b_256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_Blake2b_256_bindings))

(library
  (name lib_Hacl_Hash_Blake2s_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_Blake2s_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_Blake2s_128_bindings))

(library
  (name lib_Hacl_Hash_MD5_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_MD5-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_MD5_bindings))

(library
  (name lib_Hacl_Hash_SHA1_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_SHA1-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_SHA1_bindings))

(library
  (name lib_Hacl_Hash_SHA2_bindings)
  (public_name hacl-star-raw.lib-Hacl_Hash_SHA2-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Hash_SHA2_bindings))

(library
  (name lib_EverCrypt_AutoConfig2_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_AutoConfig2-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_AutoConfig2_bindings))

(library
  (name lib_EverCrypt_Hash_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Hash-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Hash_bindings))

(library
  (name lib_Hacl_SHA3_bindings)
  (public_name hacl-star-raw.lib-Hacl_SHA3-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_SHA3_bindings))

(library
  (name lib_Hacl_Chacha20_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20_bindings))

(library
  (name lib_Hacl_Salsa20_bindings)
  (public_name hacl-star-raw.lib-Hacl_Salsa20-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Salsa20_bindings))

(library
  (name lib_Hacl_Bignum_Base_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum_Base-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum_Base_bindings))

(library
  (name lib_Hacl_Curve25519_64_Slow_bindings)
  (public_name hacl-star-raw.lib-Hacl_Curve25519_64_Slow-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Curve25519_64_Slow_bindings))

(library
  (name lib_Hacl_Curve25519_64_bindings)
  (public_name hacl-star-raw.lib-Hacl_Curve25519_64-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Curve25519_64_bindings))

(library
  (name lib_Hacl_Bignum25519_51_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum25519_51-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum25519_51_bindings))

(library
  (name lib_Hacl_Curve25519_51_bindings)
  (public_name hacl-star-raw.lib-Hacl_Curve25519_51-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Curve25519_51_bindings))

(library
  (name lib_Hacl_Ed25519_bindings)
  (public_name hacl-star-raw.lib-Hacl_Ed25519-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Ed25519_bindings))

(library
  (name lib_Hacl_Poly1305_32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Poly1305_32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Poly1305_32_bindings))

(library
  (name lib_Hacl_Poly1305_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_Poly1305_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Poly1305_128_bindings))

(library
  (name lib_Hacl_Poly1305_256_bindings)
  (public_name hacl-star-raw.lib-Hacl_Poly1305_256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Poly1305_256_bindings))

(library
  (name lib_Hacl_NaCl_bindings)
  (public_name hacl-star-raw.lib-Hacl_NaCl-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_NaCl_bindings))

(library
  (name lib_EverCrypt_CTR_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_CTR-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_CTR_bindings))

(library
  (name lib_Hacl_P256_bindings)
  (public_name hacl-star-raw.lib-Hacl_P256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_P256_bindings))

(library
  (name lib_Hacl_Frodo_KEM_bindings)
  (public_name hacl-star-raw.lib-Hacl_Frodo_KEM-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Frodo_KEM_bindings))

(library
  (name lib_Hacl_IntTypes_Intrinsics_bindings)
  (public_name hacl-star-raw.lib-Hacl_IntTypes_Intrinsics-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_IntTypes_Intrinsics_bindings))

(library
  (name lib_Hacl_IntTypes_Intrinsics_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_IntTypes_Intrinsics_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_IntTypes_Intrinsics_128_bindings))

(library
  (name lib_Hacl_RSAPSS_bindings)
  (public_name hacl-star-raw.lib-Hacl_RSAPSS-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_RSAPSS_bindings))

(library
  (name lib_Hacl_FFDHE_bindings)
  (public_name hacl-star-raw.lib-Hacl_FFDHE-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_FFDHE_bindings))

(library
  (name lib_Hacl_Streaming_Blake2_bindings)
  (public_name hacl-star-raw.lib-Hacl_Streaming_Blake2-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Streaming_Blake2_bindings))

(library
  (name lib_Hacl_Frodo640_bindings)
  (public_name hacl-star-raw.lib-Hacl_Frodo640-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Frodo640_bindings))

(library
  (name lib_Hacl_Chacha20_Vec128_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20_Vec128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20_Vec128_bindings))

(library
  (name lib_Hacl_Chacha20Poly1305_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20Poly1305_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20Poly1305_128_bindings))

(library
  (name lib_Hacl_HMAC_bindings)
  (public_name hacl-star-raw.lib-Hacl_HMAC-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HMAC_bindings))

(library
  (name lib_Hacl_HKDF_bindings)
  (public_name hacl-star-raw.lib-Hacl_HKDF-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HKDF_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP128_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP128_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP128_SHA512_bindings))

(library
  (name lib_Hacl_SHA2_Vec256_bindings)
  (public_name hacl-star-raw.lib-Hacl_SHA2_Vec256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_SHA2_Vec256_bindings))

(library
  (name lib_Hacl_Bignum4096_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum4096-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum4096_bindings))

(library
  (name lib_Hacl_Chacha20_Vec32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20_Vec32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20_Vec32_bindings))

(library
  (name lib_EverCrypt_Ed25519_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Ed25519-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Ed25519_bindings))

(library
  (name lib_Hacl_Bignum4096_32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum4096_32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum4096_32_bindings))

(library
  (name lib_Hacl_HPKE_P256_CP128_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_P256_CP128_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_P256_CP128_SHA256_bindings))

(library
  (name lib_Hacl_Chacha20_Vec256_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20_Vec256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20_Vec256_bindings))

(library
  (name lib_Hacl_Chacha20Poly1305_256_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20Poly1305_256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20Poly1305_256_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP256_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP256_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP256_SHA512_bindings))

(library
  (name lib_Hacl_SHA2_Scalar32_bindings)
  (public_name hacl-star-raw.lib-Hacl_SHA2_Scalar32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_SHA2_Scalar32_bindings))

(library
  (name lib_Hacl_Frodo976_bindings)
  (public_name hacl-star-raw.lib-Hacl_Frodo976-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Frodo976_bindings))

(library
  (name lib_Hacl_HMAC_Blake2s_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_HMAC_Blake2s_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HMAC_Blake2s_128_bindings))

(library
  (name lib_Hacl_HKDF_Blake2s_128_bindings)
  (public_name hacl-star-raw.lib-Hacl_HKDF_Blake2s_128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HKDF_Blake2s_128_bindings))

(library
  (name lib_Hacl_GenericField64_bindings)
  (public_name hacl-star-raw.lib-Hacl_GenericField64-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_GenericField64_bindings))

(library
  (name lib_Hacl_Frodo1344_bindings)
  (public_name hacl-star-raw.lib-Hacl_Frodo1344-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Frodo1344_bindings))

(library
  (name lib_Hacl_Bignum32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum32_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP128_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP128_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP128_SHA256_bindings))

(library
  (name lib_Hacl_Bignum256_32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum256_32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum256_32_bindings))

(library
  (name lib_Hacl_SHA2_Vec128_bindings)
  (public_name hacl-star-raw.lib-Hacl_SHA2_Vec128-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_SHA2_Vec128_bindings))

(library
  (name lib_Hacl_Chacha20Poly1305_32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Chacha20Poly1305_32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Chacha20Poly1305_32_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP32_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP32_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP32_SHA256_bindings))

(library
  (name lib_Hacl_Streaming_Poly1305_32_bindings)
  (public_name hacl-star-raw.lib-Hacl_Streaming_Poly1305_32-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Streaming_Poly1305_32_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP32_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP32_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP32_SHA512_bindings))

(library
  (name lib_Hacl_HPKE_P256_CP256_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_P256_CP256_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_P256_CP256_SHA256_bindings))

(library
  (name lib_Hacl_HPKE_P256_CP32_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_P256_CP32_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_P256_CP32_SHA256_bindings))

(library
  (name lib_Hacl_Bignum64_bindings)
  (public_name hacl-star-raw.lib-Hacl_Bignum64-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Bignum64_bindings))

(library
  (name lib_Hacl_Frodo64_bindings)
  (public_name hacl-star-raw.lib-Hacl_Frodo64-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Frodo64_bindings))

(library
  (name lib_Hacl_Streaming_SHA1_bindings)
  (public_name hacl-star-raw.lib-Hacl_Streaming_SHA1-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Streaming_SHA1_bindings))

(library
  (name lib_Hacl_Streaming_MD5_bindings)
  (public_name hacl-star-raw.lib-Hacl_Streaming_MD5-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_Streaming_MD5_bindings))

(library
  (name lib_Hacl_HMAC_Blake2b_256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HMAC_Blake2b_256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HMAC_Blake2b_256_bindings))

(library
  (name lib_Hacl_HKDF_Blake2b_256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HKDF_Blake2b_256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HKDF_Blake2b_256_bindings))

(library
  (name lib_Hacl_EC_Ed25519_bindings)
  (public_name hacl-star-raw.lib-Hacl_EC_Ed25519-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_EC_Ed25519_bindings))

(library
  (name lib_Hacl_HPKE_Curve51_CP256_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve51_CP256_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve51_CP256_SHA256_bindings))

(library
  (name lib_EverCrypt_Chacha20Poly1305_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Chacha20Poly1305-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Chacha20Poly1305_bindings))

(library
  (name lib_EverCrypt_AEAD_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_AEAD-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_AEAD_bindings))

(library
  (name lib_EverCrypt_HMAC_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_HMAC-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_HMAC_bindings))

(library
  (name lib_EverCrypt_HKDF_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_HKDF-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_HKDF_bindings))

(library
  (name lib_Hacl_HMAC_DRBG_bindings)
  (public_name hacl-star-raw.lib-Hacl_HMAC_DRBG-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HMAC_DRBG_bindings))

(library
  (name lib_EverCrypt_DRBG_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_DRBG-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_DRBG_bindings))

(library
  (name lib_EverCrypt_Poly1305_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Poly1305-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Poly1305_bindings))

(library
  (name lib_EverCrypt_Curve25519_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Curve25519-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Curve25519_bindings))

(library
  (name lib_EverCrypt_Cipher_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Cipher-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Cipher_bindings))

(library
  (name lib_EverCrypt_Vale_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_Vale-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_Vale_bindings))

(library
  (name lib_EverCrypt_StaticConfig_bindings)
  (public_name hacl-star-raw.lib-EverCrypt_StaticConfig-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules EverCrypt_StaticConfig_bindings))

(library
  (name lib_Lib_RandomBuffer_System_bindings)
  (public_name hacl-star-raw.lib-Lib_RandomBuffer_System-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Lib_RandomBuffer_System_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP128_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP128_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP128_SHA256_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP128_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP128_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP128_SHA512_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP256_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP256_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP256_SHA256_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP256_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP256_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP256_SHA512_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP32_SHA256_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP32_SHA256-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP32_SHA256_bindings))

(library
  (name lib_Hacl_HPKE_Curve64_CP32_SHA512_bindings)
  (public_name hacl-star-raw.lib-Hacl_HPKE_Curve64_CP32_SHA512-bindings)
  (wrapped false)
  (libraries ctypes ctypes.stubs lib_evercrypt_so lib_Hacl_Spec_bindings lib_Hacl_Spec_stubs lib_EverCrypt_Error_bindings lib_EverCrypt_Error_stubs lib_Hacl_GenericField32_bindings lib_Hacl_GenericField32_stubs lib_Hacl_Bignum256_bindings lib_Hacl_Bignum256_stubs lib_Hacl_Hash_Blake2_bindings lib_Hacl_Hash_Blake2_stubs lib_Hacl_Streaming_SHA2_bindings lib_Hacl_Streaming_SHA2_stubs)
  (flags (:standard -warn-error -33))
  (modules Hacl_HPKE_Curve64_CP32_SHA512_bindings))

(library
  (name lib_bindings_gen)
  (public_name hacl-star-raw.lib-bindings-gen)
  (libraries lib_Hacl_Bignum_bindings
lib_Hacl_Hash_Base_bindings
lib_Hacl_Hash_Blake2b_256_bindings
lib_Hacl_Hash_Blake2s_128_bindings
lib_Hacl_Hash_MD5_bindings
lib_Hacl_Hash_SHA1_bindings
lib_Hacl_Hash_SHA2_bindings
lib_EverCrypt_AutoConfig2_bindings
lib_EverCrypt_Hash_bindings
lib_Hacl_SHA3_bindings
lib_Hacl_Chacha20_bindings
lib_Hacl_Salsa20_bindings
lib_Hacl_Bignum_Base_bindings
lib_Hacl_Curve25519_64_Slow_bindings
lib_Hacl_Curve25519_64_bindings
lib_Hacl_Bignum25519_51_bindings
lib_Hacl_Curve25519_51_bindings
lib_Hacl_Ed25519_bindings
lib_Hacl_Poly1305_32_bindings
lib_Hacl_Poly1305_128_bindings
lib_Hacl_Poly1305_256_bindings
lib_Hacl_NaCl_bindings
lib_EverCrypt_CTR_bindings
lib_Hacl_P256_bindings
lib_Hacl_Frodo_KEM_bindings
lib_Hacl_IntTypes_Intrinsics_bindings
lib_Hacl_IntTypes_Intrinsics_128_bindings
lib_Hacl_RSAPSS_bindings
lib_Hacl_FFDHE_bindings
lib_Hacl_Streaming_Blake2_bindings
lib_Hacl_Frodo640_bindings
lib_Hacl_Chacha20_Vec128_bindings
lib_Hacl_Chacha20Poly1305_128_bindings
lib_Hacl_HMAC_bindings
lib_Hacl_HKDF_bindings
lib_Hacl_HPKE_Curve51_CP128_SHA512_bindings
lib_Hacl_SHA2_Vec256_bindings
lib_Hacl_Bignum4096_bindings
lib_Hacl_Chacha20_Vec32_bindings
lib_EverCrypt_Ed25519_bindings
lib_Hacl_Bignum4096_32_bindings
lib_Hacl_HPKE_P256_CP128_SHA256_bindings
lib_Hacl_Chacha20_Vec256_bindings
lib_Hacl_Chacha20Poly1305_256_bindings
lib_Hacl_HPKE_Curve51_CP256_SHA512_bindings
lib_Hacl_SHA2_Scalar32_bindings
lib_Hacl_Frodo976_bindings
lib_Hacl_HMAC_Blake2s_128_bindings
lib_Hacl_HKDF_Blake2s_128_bindings
lib_Hacl_GenericField64_bindings
lib_Hacl_Frodo1344_bindings
lib_Hacl_Bignum32_bindings
lib_Hacl_HPKE_Curve51_CP128_SHA256_bindings
lib_Hacl_Bignum256_32_bindings
lib_Hacl_SHA2_Vec128_bindings
lib_Hacl_Chacha20Poly1305_32_bindings
lib_Hacl_HPKE_Curve51_CP32_SHA256_bindings
lib_Hacl_Streaming_Poly1305_32_bindings
lib_Hacl_HPKE_Curve51_CP32_SHA512_bindings
lib_Hacl_HPKE_P256_CP256_SHA256_bindings
lib_Hacl_HPKE_P256_CP32_SHA256_bindings
lib_Hacl_Bignum64_bindings
lib_Hacl_Frodo64_bindings
lib_Hacl_Streaming_SHA1_bindings
lib_Hacl_Streaming_MD5_bindings
lib_Hacl_HMAC_Blake2b_256_bindings
lib_Hacl_HKDF_Blake2b_256_bindings
lib_Hacl_EC_Ed25519_bindings
lib_Hacl_HPKE_Curve51_CP256_SHA256_bindings
lib_EverCrypt_Chacha20Poly1305_bindings
lib_EverCrypt_AEAD_bindings
lib_EverCrypt_HMAC_bindings
lib_EverCrypt_HKDF_bindings
lib_Hacl_HMAC_DRBG_bindings
lib_EverCrypt_DRBG_bindings
lib_EverCrypt_Poly1305_bindings
lib_EverCrypt_Curve25519_bindings
lib_EverCrypt_Cipher_bindings
lib_EverCrypt_Vale_bindings
lib_EverCrypt_StaticConfig_bindings
lib_Lib_RandomBuffer_System_bindings
lib_Hacl_HPKE_Curve64_CP128_SHA256_bindings
lib_Hacl_HPKE_Curve64_CP128_SHA512_bindings
lib_Hacl_HPKE_Curve64_CP256_SHA256_bindings
lib_Hacl_HPKE_Curve64_CP256_SHA512_bindings
lib_Hacl_HPKE_Curve64_CP32_SHA256_bindings
lib_Hacl_HPKE_Curve64_CP32_SHA512_bindings
)
  (modules)
  (wrapped false))
